export const categories = [
  {
    id: 1,
    name: "Converse Shoes1",
  },
  {
    id: 2,
    name: "Converse Shoes2",
  },
  {
    id: 3,
    name: "Converse Shoes3",
  },
  {
    id: 4,
    name: "Converse Shoes4",
  },
  {
    id: 5,
    name: "Converse Shoes5",
  },
  {
    id: 6,
    name: "Converse Shoes6",
  },
];

export const products = [
  {
    id: 1,
    categoryId: 1,
    name: "Adidas Converse1",
    media: "product.png",
    price: 1200,
  },
  {
    id: 2,
    categoryId: 1,
    name: "Adidas Converse2",
    media: "product.png",
    price: 1200,
  },
  {
    id: 3,
    categoryId: 1,
    name: "Adidas Converse3",
    media: "product.png",
    price: 1200,
  },
  {
    id: 4,
    categoryId: 1,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 5,
    categoryId: 1,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 6,
    categoryId: 1,
    name: "Adidas Converse10",
    media: "product.png",
    price: 1200,
  },
  {
    id: 7,
    categoryId: 1,
    name: "Adidas Converse11",
    media: "product.png",
    price: 1200,
  },
  {
    id: 8,
    categoryId: 1,
    name: "Adidas Converse12",
    media: "product.png",
    price: 1200,
  },
  {
    id: 9,
    categoryId: 1,
    name: "Adidas Converse13",
    media: "product.png",
    price: 1200,
  },
  {
    id: 10,
    categoryId: 1,
    name: "Adidas Converse14",
    media: "product.png",
    price: 1200,
  },

  {
    id: 11,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 12,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 13,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 14,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 15,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 16,
    categoryId: 2,
    name: "Adidas Converse24",
    media: "product.png",
    price: 1200,
  },
  {
    id: 17,
    categoryId: 2,
    name: "Adidas Converse23",
    media: "product.png",
    price: 1200,
  },
  {
    id: 18,
    categoryId: 2,
    name: "Adidas Converse22",
    media: "product.png",
    price: 1200,
  },
  {
    id: 21,
    categoryId: 3,
    name: "Adidas Converse22",
    media: "product.png",
    price: 1200,
  },
  {
    id: 22,
    categoryId: 3,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 23,
    categoryId: 3,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 24,
    categoryId: 3,
    name: "Adidas Converse32",
    media: "product.png",
    price: 1200,
  },
  {
    id: 25,
    categoryId: 3,
    name: "Adidas Converse31",
    media: "product.png",
    price: 1200,
  },
  {
    id: 26,
    categoryId: 3,
    name: "Adidas Converse35",
    media: "product.png",
    price: 1200,
  },
  {
    id: 27,
    categoryId: 3,
    name: "Adidas Converse36",
    media: "product.png",
    price: 1200,
  },
  {
    id: 28,
    categoryId: 3,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 31,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 32,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 33,
    categoryId: 4,
    name: "Adidas Converse43",
    media: "product.png",
    price: 1200,
  },
  {
    id: 34,
    categoryId: 4,
    name: "Adidas Converse46",
    media: "product.png",
    price: 1200,
  },
  {
    id: 35,
    categoryId: 4,
    name: "Adidas Converse45",
    media: "product.png",
    price: 1200,
  },
  {
    id: 36,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 37,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 38,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 41,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 42,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 43,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 44,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 45,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 46,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 47,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 48,
    categoryId: 5,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 51,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 52,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 53,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 54,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 55,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 56,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 57,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 58,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 61,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 62,
    categoryId: 6,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 63,
    categoryId: 4,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 64,
    categoryId: 7,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 65,
    categoryId: 3,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 66,
    categoryId: 1,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 67,
    categoryId: 2,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
  {
    id: 68,
    categoryId: 3,
    name: "Adidas Converse",
    media: "product.png",
    price: 1200,
  },
];

export const brands = [
  {
    id: 1,
    categoryId: 1,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
  {
    id: 2,
    categoryId: 2,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
  {
    id: 3,
    categoryId: 3,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
  {
    id: 4,
    categoryId: 4,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
  {
    id: 5,
    categoryId: 5,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
  {
    id: 6,
    categoryId: 6,
    name: "Adidda Sport wears",
    media: "shop.png",
    items: [
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
      "brandIcon.png",
    ],
  },
];
